Typo in KeyVaultClient causes invalid authorization request (#74)
* Fix invalid resource uri in REST call

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Azure("AuthorizationError(Failed to authenticate to Azure Active Directory
Caused by:
   Generic error: AADSTS70011: The provided request must include a \'scope\' input parameter. The provided value for the input parameter \'scope\' is not valid. 
   The scope https://vault.azure.net.default is not valid

* Be more tolerant w/ setting the endpoint resource url

Co-authored-by: numbers <numbers@dockerhost>